version: '3'
services:
  db:
    image: postgres
    environment:
      PGUSER="jccode"
      PGPASSWORD=""
      PGDATABASE="reviews"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  reviews-server:
    build: .
    ports:
      - '3001:8080'
    depends_on:
      - db