version: '3'

services:
  db:
      image: 'postgres'
      ports:
        - '5432:5432'
      environment:
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_USER: 'postgres'
        POSTGRES_DB: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
  server:
    image: my-app
    build: .
    ports:
      - 80:8080
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    depends_on:
      - db